CREATE TABLE egyesület (
  egyesületId INT(10) NOT NULL AUTO_INCREMENT,
  név VARCHAR(50) DEFAULT NULL,
  alapításÉve INT(10) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

CREATE TABLE verseny (
  VersenyId INT(10) NOT NULL AUTO_INCREMENT,
  Név VARCHAR(50) DEFAULT NULL,
  Távolság INT(10) DEFAULT NULL,
  Város VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (VersenyId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

CREATE TABLE sportoló (
  SportolóId INT(10) NOT NULL AUTO_INCREMENT,
  Vezetéknév VARCHAR(50) DEFAULT NULL,
  Keresztnév VARCHAR(50) DEFAULT NULL,
  SzületésiÉv SMALLINT(5) DEFAULT NULL,
  EgyesületId INT(10) DEFAULT NULL,
  Nem VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (SportolóId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

CREATE TABLE indulás (
  IndulóId INT(10) NOT NULL AUTO_INCREMENT,
  SportolóId INT(10) DEFAULT NULL,
  VersenyId INT(10) DEFAULT NULL,
  Befutott TINYINT(1) DEFAULT NULL,
  EredményPerc INT(10) DEFAULT NULL,
  EredményMásodperc INT(10) DEFAULT NULL,
  PRIMARY KEY (IndulóId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_hungarian_ci;
